const userActionTypes = {
    GET_USER_BY_ID_START: "GET_USER_BY_ID_START",
    GET_USER_BY_ID_SUCCESS: "GET_USER_BY_ID_SUCCESS",
    GET_USER_BY_ID_FAILURE: "GET_USER_BY_ID_FAILURE",
    UPDATE_USER_START:"UPDATE_USER_START",
    UPDATE_USER_SUCCESS:"UPDATE_USER_SUCCESS",
    UPDATE_USER_FAILURE:"UPDATE_USER_FAILURE",
    DELETE_USER_START:"DELETE_USER_START",
    DELETE_USER_SUCCESS:"DELETE_USER_SUCCESS",
    DELETE_USER_FAILURE:"DELETE_USER_FAILURE",
    DELETE_ALL_POSTS_OF_A_USER_START:"DELETE_ALL_POSTS_OF_A_USER_START",
    DELETE_ALL_POSTS_OF_A_USER_SUCCESS:"DELETE_ALL_POSTS_OF_A_USER_SUCCESS",
    DELETE_ALL_POSTS_OF_A_USER_FAILURE:"DELETE_ALL_POSTS_OF_A_USER_FAILURE"
  };
  
  export default userActionTypes;
  