const postActionTypes = {
    GET_ALL_POSTS_START: "GET_ALL_POSTS_START",
    GET_ALL_POSTS_SUCCESS: "GET_ALL_POSTS_SUCCESS",
    GET_ALL_POSTS_FAILURE: "GET_ALL_POSTS_FAILURE",
    GET_POST_BY_ID_START: "GET_POST_BY_ID_START",
    GET_POST_BY_ID_SUCCESS: "GET_POST_BY_ID_SUCCESS",
    GET_POST_BY_ID_FAILURE: "GET_POST_BY_ID_FAILURE",
    ADD_POST_START:"ADD_POST_START",
    ADD_POST_SUCCESS:"ADD_POST_SUCCESS",
    ADD_POST_FAILURE:"ADD_POST_FAIULURE",
    UPDATE_POST_START:"UPDATE_POST_START",
    UPDATE_POST_SUCCESS:"UPDATE_POST_SUCCESS",
    UPDATE_POST_FAILURE:"UPDATE_POST_FAIULURE",
    DELETE_POST_START:"DELETE_POST_START",
    DELETE_POST_SUCCESS:"DELETE_POST_SUCCESS",
    DELETE_POST_FAILURE:"DELETE_POST_FAIULURE"
  };
  
  export default postActionTypes;
  